### ISSUE TITLE
color_bins_layer odd output legend/hover values

### ISSUE THREAD

**Issue by makella** [CartoDB/cartoframes#724] opened 2019-06-03 18:01 UTC
@Jesus89 the two examples of odd returned values:

## First case: 
0 is returned as `< Infinity` in the legend. More curious, is that there are three bins with `< Infinity`. I looked at the results of `SELECT distinct count FROM us_primaryroads_accidents_2015 order by count` and see that the values range from 0-17.

**Details**:

- helper:
```
from cartoframes.viz.helpers import color_bins_layer

Map(
    color_bins_layer('us_primaryroads_accidents_2015', 'count')
)
```
- result
<img width="997" alt="Screen Shot 2019-06-03 at 11 41 43 AM" src="https://user-images.githubusercontent.com/1566273/58822430-b6638280-85f4-11e9-99fc-9084df064739.png">

- full table
https://cartovl.carto.com/tables/us_primaryroads_accidents_2015

## Second case
The attribute being mapped is of `loss` in dollar values from tornados between the years of 1950-2017. In this case, both the legend AND hover values are the same. Here, I am wondering why the incremental values are not indicative of the actual dollar amounts of the loss values. Could be because of too much rounding?

- helper
```
from cartoframes.viz.helpers import color_bins_layer

Map(
    color_bins_layer('tornados_1950_2017', 'loss')
)
```
- result
<img width="1152" alt="Screen Shot 2019-06-03 at 12 00 33 PM" src="https://user-images.githubusercontent.com/1566273/58823560-3985d800-85f7-11e9-8a7a-2a9963a7969d.png">

- full table
https://cartovl.carto.com/dataset/tornados_1950_2017

cc @VictorVelarde @elenatorro

**Comment by Jesus89** [comment] 2019-06-04 09:36
### First case

After testing this case, I have checked that VL returns the following values when using `globalQuantiles`:

[-Infinity, Infinity]
[-Infinity, Infinity]
[-Infinity, Infinity]
[-Infinity, 1]
[1, Infinity]

It seems that the bus is in VL then. I have changed the expression to use `globalEqIntervals` as an example. With this expression, the values make more sense:

[-Infinity, 3.40]
[3.40, 6.80]
[6.80, 10.20]
[10.20, 13.60]
[13.60, Infinity]

**Comment by Jesus89** [comment] 2019-06-04 09:39
### Second case

This is similar to the first one. 

[-Infinity, Infinity]
[-Infinity, 0.001]
[0.001, 3]
[3, 4]
[4, Infinity]

It is a VL bug, so I would open an issue there to review the `globalQuantiles` function. @VictorVelarde

**Comment by makella** [comment] 2019-06-04 17:22
thanks for taking an in-depth look and adding the issue in VL repo. What is curious is that it is working on some datasets, but not these... anyway, hope we can figure it out! switching to something like equal intervals wouldn't be my first preference. since it is working on most maps, hopefully we won't encounter this too much before we have a fix.

**Comment by elenatorro** [comment] 2019-06-10 12:16
I'm adding here two screenshots testing the helper with the current fix from [this PR](https://github.com/CartoDB/carto-vl/pull/1371) to discuss if this is the expected behaviour:

![Screenshot 2019-06-10 at 14 11 42](https://user-images.githubusercontent.com/3824953/59194683-242a2400-8b8a-11e9-8d74-2ac1d3a79dbc.png)
![Screenshot 2019-06-10 at 14 13 30](https://user-images.githubusercontent.com/3824953/59194687-255b5100-8b8a-11e9-814f-f7e42eb3a006.png)

**Comment by Jesus89** [comment] 2019-06-11 07:53
This is an improvement. If the dataset contains lots of 0's, the data scientist is responsible for fixing the data. But since we are not using Infinity anymore, the bug is fixed.

Note: I'll update from 2 to 3 the decimal places in the format function.

**Comment by Jesus89** [comment] 2019-06-11 09:03
Closed via https://github.com/CartoDB/carto-vl/pull/1371

**Closed by Jesus89** 2019-06-11 09:03 UTC
Labels: Triple Integration 🔱
