### ISSUE TITLE
[bug] cc.write(overwrite=True) affecting permissions

### ISSUE THREAD

**Issue by sabman** [CartoDB/cartoframes#543] opened 2019-02-24 20:26 UTC
For carto version `<=0.6.2` I am seeing the following strange behaviour.

If I overwrite a dataset using `cc.write(df,"dataset",overwrite=True)` then any share permissions on the updated `dataset` stop working. 

You can test it as follows:

```py
# pipenv install "cartoframes<=0.6.2" jupyter --skip-lock

import cartoframes
from cartoframes import Credentials
import pandas as pd
import requests

#  ---Setup two users one is the dataset owner the second has the dataset shared with it---
privateuser="privateuser"
private_url="https://privateuser.carto.com"
private_api_key="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

publicuser="publicuser"
public_url="https://publicuser.carto.com"
public_api_key="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

cc = cartoframes.CartoContext(base_url=private_url, api_key=private_api_key)

private_dataset = "private_table"
df = cc.read(private_dataset)

updated_df = df
updated_df.value = round(df.value*1000)

# Write and fetch
url = f'{public_url}/api/v2/sql?q=SELECT * FROM "{privateuser}".{private_dataset} LIMIT 10&api_key={public_api_key}'

# Before the write the URL works fine
r = requests.get(url) 
r.status_code == 200

cc.write(updated_df, private_dataset, overwrite = True)

# After the write the URL returns 401 permission denied
r = requests.get(url) 
r.status_code == 401
r.content
# b'{"error":["permission denied for relation private_table"]}'
```

In the rails app the ACL/Permissions record for the dataset hasn't changed. So I don't understand why it would reset the permission when querying via the sql api?

**Comment by andy-esch** [comment] 2019-02-26 15:19
@sabman, thanks for reporting -- I'm not sure why that behavior is happening. When overwriting cartoframes should respect the same privacy level.

Could you do a quick test for me:
1. Do everything up to the cc.write(... overwrite=True) steop
2. Visit the dashboard in your browser, reload it and wait about 10-20 seconds
3. Try the last three lines where you were getting the 401 error

**Comment by sabman** [comment] 2019-02-26 20:42
Thanks for the response nope that doesn't make a difference. What was the idea behind that?

**Comment by andy-esch** [comment] 2019-02-27 13:27
Visiting the dashboard in a browser triggers a metadata refresh, so I was curious if the privacy updates were set but not yet added to the account metadata. It looks like that's not the case.

We'll dig into the cartoframes code to see if we can identify the issue here.

**Comment by andy-esch** [comment] 2019-02-27 13:38
Another question: when you say 'public_api_key', do you mean that you created an api key specifically for the dataset (and maybe others) and gave the table read access? And that you are not using the master api key for the account?

**Comment by andy-esch** [comment] 2019-02-27 17:29
Ok, it's confirmed: if you create an api key for a dataset, then do a cartoframes write operation with overwrite, then that invalidates the api key/table combo.

This is a feature of the Auth API that I wasn't aware of until now. To prevent this from happening in cartoframes would require a non-trivial refactoring of the code as well. We're going to put our heads together and figure out a solution and ping back here because the behavior you are expecting is what should be in place.

cc @inigomedina

**Comment by sabman** [comment] 2019-02-27 21:41
Please let me know if I can help in anyway.

**Comment by andy-esch** [comment] 2019-03-01 16:46
cc @jorgesancha

**Comment by Jesus89** [comment] 2019-11-07 10:19
Hi @andy-esch, is this still happening with the beta version?

**Comment by andy-esch** [comment] 2019-11-07 19:52
Looks like it's still an issue. The problem seems to be that the custom key no longer has the permissions for creating a table even though its the same name as the original one. Is this an implementation of the Auth API where its more tied to some specific instance of a table (e.g., some type of unique table id) instead of just a table name? Or does the key invalidate if the table is deleted?

Permissions set for API key:
<img width="636" alt="Screen Shot 2019-11-07 at 2 20 15 PM" src="https://user-images.githubusercontent.com/1041056/68420169-c108e180-0169-11ea-9913-19658363b881.png">

Reproducible code:

```python
from cartoframes.data import Dataset
from cartoframes.auth import set_default_credentials, Credentials

set_default_credentials('eschbacher', 'custom api key')

# works as expected
df = Dataset('untitled_table_85').download()
# fails with error below
Dataset(df).upload(table_name='untitled_table_85', if_exists='replace')
```

<details><summary>Stacktrace</summary>
---------------------------------------------------------------------------
ForbiddenErrorException                   Traceback (most recent call last)
~/.local/share/virtualenvs/cartoframes-pRWzcuWT/src/carto/carto/sql.py in send(self, url, http_method, json_body, http_header)
    173                                     json=json_body)
--> 174             data_json = self.client.get_response_data(data)
    175         except CartoRateLimitException as e:

~/.local/share/virtualenvs/cartoframes-pRWzcuWT/lib/python3.7/site-packages/pyrestcli/auth.py in get_response_data(self, response, parse_json)
     50         else:
---> 51             raise BaseException.create(response)
     52 

~/.local/share/virtualenvs/cartoframes-pRWzcuWT/lib/python3.7/site-packages/pyrestcli/exceptions.py in create(response)
     37         klass = getattr(sys.modules[__name__], error)
---> 38         raise klass(message, status_code, headers, reason, url)
     39 

ForbiddenErrorException: Access denied

During handling of the above exception, another exception occurred:

CartoException                            Traceback (most recent call last)
~/git/CartoDB/cartoframes/cartoframes/data/dataset/registry/dataframe_dataset.py in _create_table(self, columns)
    103         try:
--> 104             self._context.execute_long_running_query(query)
    105         except CartoRateLimitException as err:

~/git/CartoDB/cartoframes/cartoframes/lib/context/api_context.py in execute_long_running_query(self, query)
     50     def execute_long_running_query(self, query):
---> 51         return self.batch_sql_client.create_and_wait_for_completion(query.strip())
     52 

~/.local/share/virtualenvs/cartoframes-pRWzcuWT/src/carto/carto/sql.py in create_and_wait_for_completion(self, sql_query)
    225                          json_body={"query": sql_query},
--> 226                          http_header=header)
    227 

~/.local/share/virtualenvs/cartoframes-pRWzcuWT/src/carto/carto/sql.py in send(self, url, http_method, json_body, http_header)
    177         except Exception as e:
--> 178             raise CartoException(e)
    179         return data_json

CartoException: Access denied

During handling of the above exception, another exception occurred:

CartoException                            Traceback (most recent call last)
<ipython-input-11-65c84aa6c743> in <module>
----> 1 Dataset(df).upload(table_name='untitled_table_85', if_exists='replace')

~/git/CartoDB/cartoframes/cartoframes/data/dataset/dataset.py in upload(self, with_lnglat, if_exists, table_name, schema, credentials)
    343             self._strategy.schema = schema
    344 
--> 345         self._strategy.upload(if_exists, with_lnglat)
    346 
    347         return Dataset(self._strategy.table_name, self._strategy.credentials, self._strategy.schema)

~/git/CartoDB/cartoframes/cartoframes/data/dataset/registry/dataframe_dataset.py in upload(self, if_exists, with_lnglat)
     58 
     59         if if_exists == BaseDataset.IF_EXISTS_REPLACE or not self.exists():
---> 60             self._create_table(dataframe_columns_info.columns)
     61         elif if_exists == BaseDataset.IF_EXISTS_FAIL:
     62             raise self._already_exists_error()

~/git/CartoDB/cartoframes/cartoframes/data/dataset/registry/dataframe_dataset.py in _create_table(self, columns)
    106             raise err
    107         except CartoException as err:
--> 108             raise CartoException('Cannot create table: {}.'.format(err))
    109 
    110     def _create_table_query(self, columns):

CartoException: Cannot create table: Access denied.
</details>

**Comment by Jesus89** [comment] 2019-11-08 13:41
Hi. Yesterday there was a bug related to the credentials in `develop`. I have tested your code with the new `develop` branch and it works.

Could you try again updating the `develop` branch?

**Comment by andy-esch** [comment] 2019-11-08 14:05
Once pulling latest changes, I get the same error.

I have a feeling this is expected behavior because the API key doesn't have permissions for CREATE, but it does have permissions for SELECT, INSERT, UPDATE, and DELETE (DROP in this case I think?).

And since the replace procedure happens in a sql transaction, the transaction rolls back because of the thrown error and the table is never deleted (which is a good thing outside of this specific use case). I believe that transaction happens here: https://github.com/CartoDB/cartoframes/blob/4f34105ab4354953ca4c41738b15c2a05fab63fd/cartoframes/data/dataset/registry/query_dataset.py#L90-L94

**Comment by Jesus89** [comment] 2019-11-08 14:23
Oh, I see. Could you try with your master API key?

**Comment by andy-esch** [comment] 2019-11-08 14:26
It works as expected with the master API key

**Comment by Jesus89** [comment] 2019-11-08 14:54
Great!. Do you think could we close this ticket then?

**Comment by andy-esch** [comment] 2019-11-08 14:57
No, the issue is about a use case for using a custom API key with a table. The expectation, which I think is a good one, is that replacing/overwriting a table should allow the use of the same custom API key.

**Comment by Jesus89** [comment] 2019-11-08 15:02
OK. Thanks for the clarification :)

**Comment by oleurud** [comment] 2019-11-08 15:44
Hi! As you said @andy-esch the problem is the following: the regular API key should have a `CREATE datasets` permissions in order to create a table. 

So, as you are doing a `if_exists='replace'`, you are doing:
- a DROP TABLE
- CREATE TABLE

Although the table name is the same, the initial table and the final one are not the same (in Postgres terms, the `oid` is different). Using other words: your API key has some permissions over the initial table which is dropped, but your API key has no permissions to create a new table. And the error is expected.

What you need to do is to add the `CREATE datasets` permission to your API key. From the docs (https://carto.com/developers/auth-api/guides/CARTO-Authorization/):

- CREATE datasets: allows you to create tables in the user schema by using the SQL API, and also modify or delete the tables previously created with it. It won’t allow to modify or delete a table created with a different API key, in that case, you’ll receive an Access denied error.

Let me know if you need anything else @sabman and hope that helps!

**Comment by andy-esch** [comment] 2019-11-08 15:55
@oleurud, thanks for pointing all of this out. I missed the `CREATE` option for some reason. 

Just to be clear: it's not possible to do a replace with a custom API key and this is by design for the Auth API?

I've verified that it doesn't work with this configuration:
<img width="642" alt="Screen Shot 2019-11-08 at 10 54 30 AM" src="https://user-images.githubusercontent.com/1041056/68489982-30d4a600-0216-11ea-8a57-a0fefff57c7e.png">

**Comment by oleurud** [comment] 2019-11-08 16:19
>  I missed the CREATE option for some reason.

It is a "new" option. Not sure, maybe we added it like 4 months ago.

> I've verified that it doesn't work with this configuration

Sorry, you are right! We are using Batch API and it does not work without master API key. 

Reopening it

**Comment by oleurud** [comment] 2019-11-08 16:24
So, to be clear, right now this is only possible with the master API key.

In order to solve it, I see 2 options:
- check the API key type from CARTOframes and in case of not being the master one, use the SQL client instead of the Batch API
- doing it always with SQL client (not sure if it is a good idea)

**Comment by Jesus89** [comment] 2019-11-11 17:21
Between these two options, I prefer the first one. Is there any possibility to fix this in the Batch API?

**Comment by alrocar** [comment] 2019-11-11 19:36
I think we are mixing different things on this issue.

The whole point of the issue is permissions over tables that are overwritten are lost (even when you use the master API key).

To reproduce the issue:

- Upload a dataset:

```python
from cartoframes.auth import Credentials
master_api_key_credentials = Credentials(username='aromeu', api_key=API_KEY, base_url='https://aromeu.carto.com/')
ds = Dataset(df)
ds.upload(table_name='ddddd', credentials=master_api_key_credentials, if_exists='replace')
```

- Create a regular API key with permissions over the `ddddd` dataset.
- Check the regular API key has permissions over the table:

```python
regular_credentials = Credentials(username='aromeu', api_key=REGULAR_API_KEY, base_url='https://aromeu.carto.com/')
ds = Dataset('ddddd', credentials=regular_credentials)
ds.download()
```

- Now, overwrite the table:

```python
ds = Dataset(df)
ds.upload(table_name='ddddd', credentials=master_api_key_credentials, if_exists='replace')
```

- And try to read it with the regular API key that had permissions to it:

```python
ds = Dataset('ddddd', credentials=regular_credentials)
ds.download()
```

You'll get an error like this:

```
df)
ds.upload(table_name='ddddd', credentials=credentials, if_exists='replace')
<cartoframes.data.dataset.dataset.Dataset at 0x121fdfe80>
credentials = Credentials(username='aromeu', api_key='ucmU4J58dIabVBXrn3rTvg', base_url='https://aromeu.carto.com/')
ds = Dataset('ddddd', credentials=credentials)
ds.download()
credentials = Credentials(username='aromeu', api_key='ucmU4J58dIabVBXrn3rTvg', base_url='https://aromeu.carto.com/')
ds = Dataset('ddddd', credentials=credentials)
ds.download()
​
---------------------------------------------------------------------------
ForbiddenErrorException                   Traceback (most recent call last)
~/Documents/dev/cartoframes/env/lib/python3.7/site-packages/carto/sql.py in send(self, sql, parse_json, do_post, format, **request_args)
    108 
--> 109             return self.auth_client.get_response_data(resp, parse_json)
    110         except CartoRateLimitException as e:

~/Documents/dev/cartoframes/env/lib/python3.7/site-packages/pyrestcli/auth.py in get_response_data(self, response, parse_json)
     50         else:
---> 51             raise BaseException.create(response)
     52 

~/Documents/dev/cartoframes/env/lib/python3.7/site-packages/pyrestcli/exceptions.py in create(response)
     37         klass = getattr(sys.modules[__name__], error)
---> 38         raise klass(message, status_code, headers, reason, url)
     39 

ForbiddenErrorException: Access denied

During handling of the above exception, another exception occurred:

CartoException                            Traceback (most recent call last)
~/Documents/dev/cartoframes/cartoframes/data/dataset/registry/table_dataset.py in _get_table_columns(self)
     78         try:
---> 79             table_info = self._context.execute_query(query)
     80             return [Column(c['column_name'], pgtype=c['data_type']) for c in table_info['rows']]

~/Documents/dev/cartoframes/cartoframes/lib/context/api_context.py in execute_query(self, query, parse_json, do_post, format, **request_args)
     47     def execute_query(self, query, parse_json=True, do_post=True, format=None, **request_args):
---> 48         return self.sql_client.send(query.strip(), parse_json, do_post, format, **request_args)
     49 

~/Documents/dev/cartoframes/env/lib/python3.7/site-packages/carto/sql.py in send(self, sql, parse_json, do_post, format, **request_args)
    112         except Exception as e:
--> 113             raise CartoException(e)
    114 

CartoException: Access denied

During handling of the above exception, another exception occurred:

ForbiddenErrorException                   Traceback (most recent call last)
~/Documents/dev/cartoframes/env/lib/python3.7/site-packages/carto/sql.py in send(self, sql, parse_json, do_post, format, **request_args)
    108 
--> 109             return self.auth_client.get_response_data(resp, parse_json)
    110         except CartoRateLimitException as e:

~/Documents/dev/cartoframes/env/lib/python3.7/site-packages/pyrestcli/auth.py in get_response_data(self, response, parse_json)
     50         else:
---> 51             raise BaseException.create(response)
     52 

~/Documents/dev/cartoframes/env/lib/python3.7/site-packages/pyrestcli/exceptions.py in create(response)
     37         klass = getattr(sys.modules[__name__], error)
---> 38         raise klass(message, status_code, headers, reason, url)
     39 

ForbiddenErrorException: Access denied

During handling of the above exception, another exception occurred:

CartoException                            Traceback (most recent call last)
<ipython-input-13-462c69de0279> in <module>
      1 credentials = Credentials(username='aromeu', api_key='ucmU4J58dIabVBXrn3rTvg', base_url='https://aromeu.carto.com/')
      2 ds = Dataset('ddddd', credentials=credentials)
----> 3 ds.download()

~/Documents/dev/cartoframes/cartoframes/data/dataset/dataset.py in download(self, limit, decode_geom, retry_times)
    225         """
    226 
--> 227         return self._strategy.download(limit, decode_geom, retry_times)
    228 
    229     IF_EXISTS_FAIL = BaseDataset.IF_EXISTS_FAIL

~/Documents/dev/cartoframes/cartoframes/data/dataset/registry/table_dataset.py in download(self, limit, decode_geom, retry_times)
     31     def download(self, limit, decode_geom, retry_times):
     32         self._is_ready_for_dowload_validation()
---> 33         columns = self._get_table_columns()
     34         query = self._get_read_query(columns, limit)
     35         self._df = self._copyto(columns, query, limit, decode_geom, retry_times)

~/Documents/dev/cartoframes/cartoframes/data/dataset/registry/table_dataset.py in _get_table_columns(self)
     84             # this may happen when using the default_public API key
     85             if str(e) == 'Access denied':
---> 86                 return self._get_query_columns()
     87             else:
     88                 raise e

~/Documents/dev/cartoframes/cartoframes/data/dataset/registry/base_dataset.py in _get_query_columns(self)
    193     def _get_query_columns(self):
    194         query = 'SELECT * FROM ({}) _q LIMIT 0'.format(self.get_query())
--> 195         table_info = self._context.execute_query(query)
    196         return Column.from_sql_api_fields(table_info['fields'])
    197 

~/Documents/dev/cartoframes/cartoframes/lib/context/api_context.py in execute_query(self, query, parse_json, do_post, format, **request_args)
     46 
     47     def execute_query(self, query, parse_json=True, do_post=True, format=None, **request_args):
---> 48         return self.sql_client.send(query.strip(), parse_json, do_post, format, **request_args)
     49 
     50     def execute_long_running_query(self, query):

~/Documents/dev/cartoframes/env/lib/python3.7/site-packages/carto/sql.py in send(self, sql, parse_json, do_post, format, **request_args)
    111             raise e
    112         except Exception as e:
--> 113             raise CartoException(e)
    114 
    115 

CartoException: Access denied
```

So, this is not a problem on CARTOframes but in our Auth API. There are different things we could do from CARTOframes, the easiest one would be use `TRUNCATE` instead of `DROP/CREATE` for the overwrite strategy. It has the advantage that we keep permissions on the tables, but we cannot allow changing the table schema.

See related issues:
- https://github.com/CartoDB/support/issues/2021
- https://github.com/CartoDB/cartoframes/issues/780
-------------------------------------------------------------------------------------------------

About regular API keys and batch API (this is a completely different topic):
- https://github.com/CartoDB/CartoDB-SQL-API/issues/621
- https://github.com/CartoDB/product/issues/321

**Comment by alrocar** [comment] 2019-11-14 09:31
I've been thinking about the original issue and we could add an `if_exists='truncate'` option, that would TRUNCATE instead of DROP and CREATE, so for the cases when you just want to replace the data and not the schema it'd preserve the existing permissions on the table.

Thoughts?

**Comment by Jesus89** [comment] 2019-11-14 10:03
I N T E R E S T I N G

**Comment by oleurud** [comment] 2019-11-14 10:43
I like the idea. We could even move deeper doing the truncate the default one and making the DROP + CREATE the "special" case

**Comment by Jesus89** [comment] 2020-05-14 14:10
Fixed in https://github.com/CartoDB/cartoframes/pull/1633, https://github.com/CartoDB/cartoframes/pull/1628. Release 1.0.3

**Closed by Jesus89** 2020-05-14 14:10 UTC
Labels: bug, triage, version: 1.0
