### ISSUE TITLE
Issues with Onpremise 3.0.3 

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartoframes#1384] opened 2019-12-18 09:24 UTC
* This was tested using Onpremise 3.0.3
* These issues don't happen when using a cloud account. 
* Using cartoframes from devop branch

## Property with an incorrect type sqrt() error

When following the Quickstart Guide and using an Onprem account, I got the next error when using a geocoded dataframe with the size_continuos_layer helper function: `[Property with an incorrect type] sqrt(): invalid first parameter 'x' expected type was 'number', actual type was 'category'`

![Screenshot 2019-12-18 at 10 16 20](https://user-images.githubusercontent.com/11177693/71072792-7bcfca80-217f-11ea-816a-61a500cde4f2.png)

## JSONDecodeError: Expecting value: line 1 column 1 (char 0) 

Also following the steps of the Quickstart, after obtaining the geocoded dataframe, I use the methods to create Isochrones:

```
from cartoframes.data.services import Isolines

isochrones_cdf, _ = Isolines().isochrones(stores_cdf, [15*60], mode='walk')
isochrones_cdf.head()
```

```python
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-32-91515739419c> in <module>
      1 from cartoframes.data.services import Isolines
      2 
----> 3 isochrones_cdf, _ = Isolines().isochrones(stores_cdf, [15*60], mode='walk')
      4 isochrones_cdf.head()

~/Desktop/cf_release_test/env/lib/python3.7/site-packages/cartoframes/data/services/isolines.py in isochrones(self, source, ranges, **args)
     65             ``cartodb_id`` column.
     66         """
---> 67         return self._iso_areas(source, ranges, function='isochrone', **args)
     68 
     69     def isodistances(self, source, ranges, **args):

~/Desktop/cf_release_test/env/lib/python3.7/site-packages/cartoframes/data/services/isolines.py in _iso_areas(self, source, ranges, dry_run, table_name, if_exists, is_destination, mode, mode_type, mode_traffic, resolution, maxpoints, quality, exclusive, function, geom_col, source_col)
    186 
    187         # Execute and download the query to generate the isolines
--> 188         cdf = read_carto(sql, self._credentials)
    189 
    190         if exclusive:

~/Desktop/cf_release_test/env/lib/python3.7/site-packages/cartoframes/io/carto.py in read_carto(source, credentials, limit, retry_times, schema, index_col, decode_geom)
     44     context_manager = ContextManager(credentials)
     45 
---> 46     df = context_manager.copy_to(source, schema, limit, retry_times)
     47 
     48     cdf = CartoDataFrame(df, crs='epsg:4326')

~/Desktop/cf_release_test/env/lib/python3.7/site-packages/cartoframes/core/managers/context_manager.py in copy_to(self, source, schema, limit, retry_times)
     43         columns = self._get_query_columns_info(query)
     44         copy_query = self._get_copy_query(query, columns, limit)
---> 45         return self._copy_to(copy_query, columns, retry_times)
     46 
     47     def copy_from(self, cdf, table_name, if_exists='fail', cartodbfy=True, log_enabled=True):

~/Desktop/cf_release_test/env/lib/python3.7/site-packages/cartoframes/core/managers/context_manager.py in _copy_to(self, query, columns, retry_times)
    235 
    236         try:
--> 237             raw_result = self.copy_client.copyto_stream(copy_query)
    238         except CartoRateLimitException as err:
    239             if retry_times > 0:

~/Desktop/cf_release_test/env/lib/python3.7/site-packages/carto/sql.py in copyto_stream(self, query)
    517         :raise: CartoException
    518         """
--> 519         return ResponseStream(self.copyto(query))

~/Desktop/cf_release_test/env/lib/python3.7/site-packages/carto/sql.py in copyto(self, query)
    455             if 400 <= response.status_code < 500:
    456                 # Client error, provide better reason
--> 457                 reason = response.json()['error'][0]
    458                 error_msg = u'%s Client Error: %s' % (response.status_code,
    459                                                       reason)

~/Desktop/cf_release_test/env/lib/python3.7/site-packages/requests/models.py in json(self, **kwargs)
    895                     # used.
    896                     pass
--> 897         return complexjson.loads(self.text, **kwargs)
    898 
    899     @property

~/.pyenv/versions/3.7.4/lib/python3.7/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    346             parse_int is None and parse_float is None and
    347             parse_constant is None and object_pairs_hook is None and not kw):
--> 348         return _default_decoder.decode(s)
    349     if cls is None:
    350         cls = JSONDecoder

~/.pyenv/versions/3.7.4/lib/python3.7/json/decoder.py in decode(self, s, _w)
    335 
    336         """
--> 337         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338         end = _w(s, end).end()
    339         if end != len(s):

~/.pyenv/versions/3.7.4/lib/python3.7/json/decoder.py in raw_decode(self, s, idx)
    353             obj, end = self.scan_once(s, idx)
    354         except StopIteration as err:
--> 355             raise JSONDecodeError("Expecting value", s, err.value) from None
    356         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Jesus89** [comment] 2020-01-15 16:48
I'll wait until next week to test this with @oriolbx

**Comment by Jesus89** [comment] 2020-01-22 17:51
Hi @oriolbx, I'll be available on Monday. Let's see this then.

**Comment by Jesus89** [comment] 2020-06-17 06:55
Reviewing the old tickets. We were not able to reproduce this one, so closing it for now

**Closed by Jesus89** 2020-06-17 06:55 UTC
Labels: bug, triage
