### ISSUE TITLE
Shapely and Fiona dependencies failing on Windows

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartoframes#1386] opened 2019-12-18 13:51 UTC
* Issue reproduced using Windows 7 and Conda environment

It looks like we're using shapely version 1.6.x. However, there are no versions 1.6 distributions suitable for Windows on PyPI.

Because of this, the installation of beta versions CARTOframes is failing on Windows. Windows users can't install the beta versions because it can't find the Shapely version 1.6.x module.

I installed with pip Shapely version 1.4.1, but then the Fiona library failed during the installation process because it can't find Fiona 1.8 module.

<img width="484" alt="Screenshot 2019-12-18 at 14 50 26" src="https://user-images.githubusercontent.com/11177693/71091653-c9f7c480-21a5-11ea-8f58-b0a8b66cc641.png">

**Comment by Jesus89** [comment] 2019-12-18 18:07
Hi @oriolbx, thanks for the report.

Have you tried installing `geopandas` in Windows? And, what version of `Python` and `pip` are you using?

**Comment by oriolbx** [comment] 2019-12-19 09:10
I will try to install geopandas. I was using the latest pip version

**Comment by oriolbx** [comment] 2019-12-19 13:33
I get the same error using geopandas in windows:

<img width="482" alt="Screenshot 2019-12-19 at 14 31 02" src="https://user-images.githubusercontent.com/11177693/71177505-7a300080-226c-11ea-9959-039256f91259.png">


The exact pip version is 19.3.1. Python version 3.7

**Comment by Jesus89** [comment] 2019-12-19 13:37
OK, Thanks for the tests!

In that case, I think we should report the bug to both Shapely and Fiona.

Have you found this bug @andy-esch @arredond?

**Comment by arredond** [comment] 2019-12-19 15:31
I never ran into this 🤷‍♂

**Comment by andy-esch** [comment] 2019-12-27 14:38
Same, I haven't seen this one

**Comment by Jesus89** [comment] 2019-12-30 13:50
Since it's a bug related to CARTOframes dependencies, we can close this ticket open new tickets in shapely / fiona repositories.

**Comment by cmongut** [comment] 2020-01-19 19:44
Hi @oriolbx,

I was able to reproduce this issue in Windows and it was fixed by installing fiona from conda:
`conda install -c conda-forge fiona`

Could you check if this solves the issue on your side?

**Comment by oriolbx** [comment] 2020-01-21 13:36
I can install Fiona with the command that you mention @cmongut . However, after that I can't install CARTOframes with conda or with pip.

**Comment by oriolbx** [comment] 2020-01-21 13:36
What steps did you follow to install Fiona and CARTOframes?

**Comment by cmongut** [comment] 2020-01-23 12:14
I installed CARTOframes first and then Fiona so I didn't see the issue you mention. What is the error you are getting installing CARTOframes when Fiona is already installed?

**Comment by oriolbx** [comment] 2020-01-23 13:01
Is the same as before. After installing fiona with conda-forge I has to install CARTOframes with pip, and then the error appeared again

**Comment by jorisvandenbossche** [comment] 2020-02-03 11:25
The reason that the `pip install shapely` is failing on Windows, is because shapely did not have binary wheels for Windows (so it tried to build it locally, but then you need GEOS and a compiler installed, which is typically not the case). 
But, this should be solved with the latest Shapely release from a few days ago (1.7), which now added binary wheels for windows: https://pypi.org/project/Shapely/#files

That said, to make it easier for people to install CARTOframes with conda, I would recommend to create a conda-forge package (see https://github.com/CartoDB/cartoframes/issues/363). That way they don't have to use a mixture of pip and conda. 

That said, the pip install shapely

**Comment by oriolbx** [comment] 2020-02-03 13:56
Thanks a lot for the info @jorisvandenbossche :) 

So, if I understood you correctly. We should install first  Shapely version 1.7.0 and , once it is installed, install cartoframes.

Unfortunately, CARTOframes returns an error when it tries to install Fiona. I will try to install Fiona with  conda-forge after installing Shapely version 1.7.0 and then, I will install CARTOframes

**Comment by jorisvandenbossche** [comment] 2020-02-03 14:45
> Unfortunately, CARTOframes returns an error when it tries to install Fiona. I will try to install Fiona with conda-forge after installing Shapely version 1.7.0 and then, I will install CARTOframes

Hmm, I thought fiona should have binary wheels available (it's the same reason as I explained above: it is trying to build fiona from source on your machine). 
Note: you can also use conda-forge to install both shapely and fiona (which I would recommend on Windows)

**Comment by oriolbx** [comment] 2020-02-03 16:22
I managed to install CARTOframes applying the next steps:

1. Install Shapely with `pip install shapely`
2. Install Fiona with `conda install -c conda-forge fiona`
3. Install CARTOframes with `pip install cartoframes`

Thanks for the help @jorisvandenbossche !

**Comment by cmongut** [comment] 2020-02-05 10:04
Thanks both! Closing this and adding priority to adding it to conda-forge, #363.

**Closed by cmongut** 2020-02-05 10:04 UTC
Labels: bug, triage
