### ISSUE TITLE
Allow disabling base64 encoding

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartoframes#1438] opened 2020-01-03 16:48 UTC
Context
======

We're using base64 encoding system to encode and decode the Dataframes into GeoJSON format for local visualizations. This is really useful, specially when sharing the notebooks, cause the size of the generated visualizations decreases significantly due to the resulting GeoJSON can be very huge.

However, base64 has some limits. We've found a case where the visualization is not displayed cause base64 is not enough to encode all the GeoJSON information.

I think the best option here is to keep using base64 by default, but allow the user to disable the encoding in case it reaches the limit.

**Comment by Jesus89** [comment] 2020-01-13 17:14
Hi :wave: 

I have been testing the original notebook and I'm not able to reproduce the issue. I have tested `Beta 7` and `RC 1` versions and it works OK.

I have tested the size of the notebook too with and without compression: 6.81 MB compressed vs 27.1 MB without gzip compression. It would be nice to check if the bug happens with a previous version or in what conditions so we can evaluate the fix if required.

**Comment by Jesus89** [comment] 2020-01-13 17:16
Note: base64 is required to encode the result of the gzip compression, which is a binary output.

**Comment by Jesus89** [comment] 2020-01-16 16:51
I think this could depend on the operating system, I can not reproduce the issue on my computer (Linux). Maybe it only happens in Mac OS. :thinking: @arredond could you check that?

**Comment by arredond** [comment] 2020-01-20 13:57
I've certainly checked it happens on my own machine (which is a Mac) and also on Elena's (which is also a Mac). It's quite likely that the person that initially uncovered this was _also_ using a Mac.

Is there anything else I can help with here? Maybe we can try to debug it together on my machine @Jesus89

**Comment by Jesus89** [comment] 2020-01-20 14:13
Cool. Let's debug it together tomorrow. Thanks.

**Comment by Jesus89** [comment] 2020-03-03 15:55
Closed in https://github.com/CartoDB/cartoframes/pull/1536

**Closed by Jesus89** 2020-03-03 15:55 UTC
Labels: New Feature, bug, discuss, triage
