### ISSUE TITLE
Easy way to create isolines

### ISSUE THREAD

**Issue by cmongut** [CartoDB/cartoframes#889] opened 2019-08-01 13:25 UTC
Right now, creating isolines from a dataset forces a data scientist to learn the SQL API. We can provide a handy method instead like:
Analysis.isolines(dataset, ...)

**Comment by jgoizueta** [comment] 2019-09-10 14:08
As always, I'm agonising about the silly details of function return values:

This works as follows:

There's two methods in the `Isolines` class, `isochrones` and `isodistances`. Both have same arguments and result.

First argument is either a `Dataset` or a `DataFrame`. Second is an array of range values (seconds for isochrones and meters for isodistances)

We can get the credits needed for the work with a dry run:
```python
iso.isochrones(dataset, [600,3600], mode='car', dry_run=True)
```

We can actually do the work and obtain the results as a Dataframe:
```python
df = iso.isochrones(dataset, [600,3600], mode='car')
```

The resulting dataframe has a `source_id` column that links to the input records (1:N), a `center` geometry (the input points),
`data_range` with the range value and `the_geom` with the corresponding isoline geometry.

We can ask to keep the results in a table with:
```python
ds = iso.isochrones(dataset, [600,3600], mode='car', table_name='nearby_zones')
```

Now, my usual doubts: the initial implementation always returns a `Dataset` when the results have been saved to a table (`table_name`)
and a `DataFrame` otherwise;
* Should we return a `DataFrame` when input is a Dataframe even if we generate a table?
* Should we return a `Dataset` when input is a Dataset even if we don't save the results to a table?
* Should we always return a `DataFrame`?
* Should we always return a `Dataset`?

Another question I haven't looked at yet is returning metadata/information besides the result data (as done for geocoding).

**Comment by cmongut** [comment] 2019-09-10 15:10
> * Should we return a `DataFrame` when input is a Dataframe even if we generate a table?
Yes, I would do that.
> * Should we return a `Dataset` when input is a Dataset even if we don't save the results to a table?
Yeap.
> * Should we always return a `DataFrame`?
> * Should we always return a `Dataset`?
If we accept datasets and dataframes as inputs, I think the output should have the same type.

@alejandrohall could you confirm this?

**Comment by jgoizueta** [comment] 2019-09-23 10:37
With the experience of having defined the Geocode interface the idea is know to support both DataFrame and Dataset as inputs, return a value of the same type as the input, and produce persistent table dataset results only if a `table_name` parameter is passed.

But I still have some doubts about the options we have to relate the results to the input source points, let's see:

Isochrones/Isodistances take two mandatory arguments:
* `source`: a points dataset/dataframe; these are the source points for the areas to be computed
* `ranges`: an array of range values (seconds of travel time for isochrones, meters of travel for isodistances)

It computes the areas that are within travel range (time/distance) from the source points for every range and source point value. So for each input point we have an area for every range value. These areas are returned as a new dataset/dataframe.

I added two options, `with_source_id` and `with_source_geom` (inspired by the camshaft, trade areas analysis, AKA known as travel buffers) that determine how each produced area is associated to the corresponding source point:
* By default `with_source_id` is True, which means that the result has a `source_id` column with the id (cartodb_id) of the source points. (this is called `source_cartodb_id` in camshaft). This makes sense when the input is a dataset. It allows to join the areas to its sources. It may or may not make sense for a Query; it requires the query to include a `cartodb_id`. For DataFrames it would make sense if we store index values from the source dataframe in it (which is not being done ATM)
* The other option, `with_source_geom` includes a duplicate of the input source geometries in the output (called `center` in camshaft). This could be handy in some cases so we can use only the result for visualization of input points, but in general I think (at least for tables) it will be more common/useful  to use a joint to the source dataset with all its attributes.

I would appreciate any feedback on this, do those parameters make sense? Should we support joining source/result dataframes (when tables are not used) by index?

@cmongut maybe we should have another data-scientists survey... 
cc @makella

**Comment by jgoizueta** [comment] 2019-09-23 10:58
Regarding the naming and what  @makella and @elenatorro have commented in the PR, I have two alternative proposals.

### Geocode-style naming: classes that provide services.

* Have a base class (implementation detail) called `data.services.Routing` which provides routing services.
* Have a `Isochrones` derived class providing a single method `isocrone_area`.
* Have a `Isodistances` derived class providing a single method `isodistance_area`.

I'd add the `_area` suffix to make evident that areas, rather than lines are produced.

I've also considered naming the derived classes as `TravelTime` and `TravelDistance`.

Example:
```python
from cartoframes.services.routing import Isochrone
isochrone_service = Isochrone(credentials)
result = isochrone_service.isocrone_area(source_points, ranges=[100, 1000], travel_mode='car')
```

An advantage I see in using classes and methods is that optional parameters like credentials seem to feet well in the class constructors, then variants of the service could be implemented as different methods with different parameters.

### Classes to represent the operation/result

We could have a base implementation class `Routing` as before, but then use the instance of the derived classes to represent the results, using the class constructors to pass all parameters. We would have classes `IsochroneArea` and `IsodistanceArea`

Example:
```python
from cartoframes.services.routing import IsochroneArea
result = IsochroneArea(source_points, ranges=[100, 1000], travel_mode='car', credentials=credentials)
```

The advantage I see here is that the result object can combine clearly result data and metadata (credits, used...)

**Comment by jgoizueta** [comment] 2019-09-24 07:17
More naming ramblings

Just after having renamed the methods as `isochrone_areas` and `isodistance_areas` I've realized they're not strictly correct: they're not areas of equal value, rather areas enclosed by equal-value lines, or areas of value equal or less than their range value. I still like the names, though, and maybe I'm just knit-picking here; I've seen equally inaccurate terms like *areas of equal travel time* in common use. Other terms I've seen: *isolines polygons*, *service areas* 

Now, here are some more alternatives that I like:
* `travel_time_ranges` and `travel_distance_ranges`
* `travel_time_areas` and `travel_distance_areas`

**Comment by alasarr** [comment] 2019-09-24 10:57
I'll go with the original approach:

```python
from cartoframes.data.services import Isolines
iso = Isolines(credentials)
iso.isochrones(dataset, [600,3600], mode='car', dry_run=True)
iso. isodistances(dataset, [600,3600], mode='car', dry_run=True)
```

The class approach overcomplicates too much to have at the end 1 class with 1 method. Users will have to understand lots of classes.

**Comment by cmongut** [comment] 2019-09-24 12:04
👋 Here it's the feedback after talking with 4 people from CARTO:
- 2 data scientists thought about using isolines for this concept. (They didn't have to use it before CARTO so they can be a bit biased)
- 1 customer support team mate told me that they use the term "area of influence". Sometimes they use buffer if the customer knows about GIS.
- 1 customer success manager told me that they also use the term "area of influence". They think it's a name that everyone understands and isolines is for GIS people.

It seems we have an issue here but I wouldn't try to tackle it now because I am sure we will have other issues with other names. I agree to continue with the current naming :)

**Comment by alasarr** [comment] 2019-09-24 13:20
>1 customer support team mate told me that they use the term "area of influence". Sometimes they use buffer if the customer knows about GIS.

Wrong, if the user knows about GIS, a buffer is a buffer, not an isoline. If the user knows about GIS, isoline is the word on GIS.

>1 customer success manager told me that they also use the term "area of influence". They think it's a name that everyone understands and isolines is for GIS people.

I think this is more for customers who have not development skills. A developer wants something more specific.

**Comment by jgoizueta** [comment] 2019-09-25 10:46
I want to discuss here the return values of analyses methods in general.

The geocoding analysis returns a tuple with the result data and metadata. Initially I was using a single result for isochrones (metadata for dry runs, data otherwise), but we're going to need metadata also for dry runs, and I'd like to use a consistent approach for all (current and future) analyses, and also avoid having the form of the result vary depending on the arguments passed.

After considering some alternatives I propose using a [`named tuple`](https://docs.python.org/3/library/collections.html#collections.namedtuple) (also supported for [Python 2](https://docs.python.org/2/library/collections.html#collections.namedtuple))
with two named fields, the first for `data` and the second for `metadata` (`information` ?).
The first one can be a `Dataset` or a `DataFrame`, and the second one a dictionary.
That would allow current usage in geocoding examples to still be valid:

```python
dataset, info = gc.geocode(...)
```

Then, if we're only insterested in the dataset we can:
```python
dataset = gc.geocode(...).data
```

Which I find more pleasant (and less error-prone) than `dataset = gc.geocode(...)[0]`.

And we can also:

```python
result = gc.geocode(...)
print(result.metadata.get('required_quota'))
print(result.data)
```

Now, a variant of this would be return the metadata as fields in the result tuple:

```python
result = gc.geocode(...)
print(result.required_quota)
print(result.data)
```

But then we need to change the original unpack usage `dataset, info = ...` to:

```python
info = gc.geocode(...)
dataset = info.data
```

**Comment by jgoizueta** [comment] 2019-09-25 15:37
So far I'm using a custom simple class instead of the `namedtuple`, so we can have a little more flexibility with results:

```python
# Compatible with original tuple result:
dataset, info = gc.geocode(...)
print(info['required_quota'])

# Can use named attributes to get only one element
dataset = gc.geocode(...).data        # May get a dataframe!
dataset = gc.geocode(...).dataset     # Error if not dataset
dataframe = gc.geocode(...).data      # May get a dataset!
dataframe = gc.geocode(...).dataframe # Error if not dataframe
quota = gc.geocode(...).metadata.get('required_quota')

# metadata attributes can also be accessed directly
quota = gc.geocode(...).get('required_quota')

# select method for convenience (*destructuring*)
dataset, quota = gc.geocode(...).select('dataset', 'required_quota')
```

What do you think?

**Comment by alasarr** [comment] 2019-09-25 17:42
I like the idea of `namedtuple`. I will avoid a custom class because it adds some complexity to the user to understand the structure of the response. `namedtuple` is standard, it's easier to understand and it's useful enough for what we want to do.

**Comment by andy-esch** [comment] 2019-09-25 19:26
Big thumbs up on namedtuple. Great idea @jgoizueta.

**Comment by jgoizueta** [comment] 2019-09-26 10:55
OK, so to be clear regarding namedtuple vs my [custom class](https://github.com/CartoDB/cartoframes/blob/faeb084b0e206b0c56e78246e662e4b5b1ef58e0/cartoframes/data/services/service.py#L14-L92), the only differences are:

* With the custom class you can have the `data` alias `dataframe`/`dataset` to be specific about the contained data type.
* With the custom class you can `result.get('required_data')`, with namedtuple you have to `result.metadata.get('required_data')`
* With the custom class you can use `select` to assign to multiple variables `d, q = result.select('data', 'required_quota')` 

I like those conveniences, but if you think it's better to stick to simpler, standard types I can live without them.

**Comment by oleurud** [comment] 2019-09-26 15:26
I think the most common use case will be:
```
data, info = dataservices_function()
```
So, if the previous assumption is real since both solutions supports that, the results are basically the same: the users will be able to get the info without thinking too much. If I need to choose one, will choose the custom one, because it can be used in most important cases like a `namedtuple` but having more features. 

In any case, I will move the PR forward with one or another because IMO it is a very small implementation detail that can be changed easily :)

**Comment by oleurud** [comment] 2019-09-26 15:49
Also, we should do the same in the enrichment functions 

cc @alejandrohall

**Comment by alasarr** [comment] 2019-09-27 10:48
Got it @jgoizueta! The result option is not bad but I prefer the `namedtuple`

**Closed** 2019-10-02 15:14 UTC
