### ISSUE TITLE
'Connection closed by server: input data too slow'

### ISSUE THREAD

**Issue by djfan** [CartoDB/cartoframes#908] opened 2019-08-13 17:24 UTC
cartoframes version: `1.0b1` 

when I `write` a dataframe with shape `(159811, 26)`, it failed with this Error Message

```
CartoException: [u'Connection closed by server: input data too slow']

CartoExceptionTraceback (most recent call last)
<command-3936245970158062> in <module>()
----> 1 dj.write(data8, 'data8_sample', overwrite=True)

/local_disk0/pythonVirtualEnvDirs/virtualEnv-815f9d21-7f16-4535-965c-e17131b11050/local/lib/python2.7/site-packages/cartoframes/context.pyc in write(self, df, table_name, temp_dir, overwrite, lnglat, encode_geom, geom_col, **kwargs)
    349             if_exists = Dataset.REPLACE
    350 
--> 351         dataset.upload(with_lnglat=lnglat, if_exists=if_exists, table_name=table_name, context=self)
    352 
    353         tqdm.write('Table successfully written to CARTO: {table_url}'.format(

/local_disk0/pythonVirtualEnvDirs/virtualEnv-815f9d21-7f16-4535-965c-e17131b11050/local/lib/python2.7/site-packages/cartoframes/data/dataset.pyc in upload(self, with_lnglat, if_exists, table_name, schema, context)
    419                 raise already_exists_error
    420 
--> 421             self._copyfrom(with_lnglat)
    422 
    423         elif self._query is not None:

/local_disk0/pythonVirtualEnvDirs/virtualEnv-815f9d21-7f16-4535-965c-e17131b11050/local/lib/python2.7/site-packages/cartoframes/data/dataset.pyc in _copyfrom(self, with_lnglat)
    553             """COPY {table_name}({columns},the_geom)
    554                FROM stdin WITH (FORMAT csv, DELIMITER '|');""".format(table_name=self._table_name, columns=columns),
--> 555             self._rows(self._df, [c for c in self._df.columns if c != 'cartodb_id'], with_lnglat, geom_col)
    556         )
    557 

/local_disk0/pythonVirtualEnvDirs/virtualEnv-815f9d21-7f16-4535-965c-e17131b11050/local/lib/python2.7/site-packages/carto/sql.pyc in copyfrom(self, query, iterable_data, compress, compression_level)
    382             raise e
    383         except Exception as e:
--> 384             raise CartoException(e)
    385 
    386         return response_json

CartoException: [u'Connection closed by server: input data too slow']
```

**Comment by oleurud** [comment] 2019-09-10 10:27
Hi @djfan 

SQL API returns that error in the copy from endpoint when a stream of data starts but the API is not receiving data for some seconds (15 seconds now if I am not wrong). So, is it a punctual error? or is it happening all the time in a specific case?

**Comment by oleurud** [comment] 2019-09-16 07:40
Ok! Thanks @djfan

**Comment by djfan** [comment] 2019-10-22 12:02
Hi @oleurud, it happened again. I used Spark to process the data in GCP Dataproc (Notebook Env) and transformed the Spark Dataframe to a Pandas Dataframe. Then uploaded the data to my account `Dataset(data8).upload(table_name='appearhere_data8', credentials=dj, if_exists="replace")`. But it failed again. 
<img width="1019" alt="Screen Shot 2019-10-22 at 8 00 34 AM" src="https://user-images.githubusercontent.com/13675438/67283747-3a35e280-f4a2-11e9-8857-1135574abf2a.png">
<img width="1148" alt="Screen Shot 2019-10-22 at 8 00 24 AM" src="https://user-images.githubusercontent.com/13675438/67283751-3d30d300-f4a2-11e9-8fdf-6e5a1e1a43e7.png">



```
/opt/conda/anaconda/lib/python3.6/site-packages/carto/sql.py:229: UserWarning: Batch SQL job created with job_id: eb61c999-745e-457a-a467-24359a5bc428
  warnings.warn('Batch SQL job created with job_id: {job_id}'.format(job_id=data['job_id']))

---------------------------------------------------------------------------
BadRequestException                       Traceback (most recent call last)
/opt/conda/anaconda/lib/python3.6/site-packages/carto/sql.py in copyfrom(self, query, iterable_data, compress, compression_level)
    379                                         stream=True)
--> 380             response_json = self.client.get_response_data(response)
    381         except CartoRateLimitException as e:

/opt/conda/anaconda/lib/python3.6/site-packages/pyrestcli/auth.py in get_response_data(self, response, parse_json)
     50         else:
---> 51             raise BaseException.create(response)
     52 

/opt/conda/anaconda/lib/python3.6/site-packages/pyrestcli/exceptions.py in create(response)
     37         klass = getattr(sys.modules[__name__], error)
---> 38         raise klass(message, status_code, headers, reason, url)
     39 

BadRequestException: ['Connection closed by server: input data too slow']

During handling of the above exception, another exception occurred:

CartoException                            Traceback (most recent call last)
<ipython-input-6-f4c2c9527e84> in <module>
      2 ## upload                  ##
      3 #############################
----> 4 Dataset(data8).upload(table_name='appearhere_data8', credentials=dj, if_exists="replace")

/opt/conda/anaconda/lib/python3.6/site-packages/cartoframes/data/dataset/dataset.py in upload(self, with_lnglat, if_exists, table_name, schema, credentials)
    271             self._strategy.schema = schema
    272 
--> 273         self._strategy.upload(if_exists, with_lnglat)
    274 
    275         return Dataset(self._strategy.table_name, self._strategy.credentials, self._strategy.schema)

/opt/conda/anaconda/lib/python3.6/site-packages/cartoframes/data/dataset/registry/dataframe_dataset.py in upload(self, if_exists, with_lnglat)
     59             raise self._already_exists_error()
     60 
---> 61         self._copyfrom(dataframe_columns_info, with_lnglat)
     62 
     63     def delete(self):

/opt/conda/anaconda/lib/python3.6/site-packages/cartoframes/data/dataset/registry/dataframe_dataset.py in _copyfrom(self, dataframe_columns_info, with_lnglat)
     86         data = _rows(self._df, dataframe_columns_info, with_lnglat)
     87 
---> 88         self._context.upload(query, data)
     89 
     90     def _create_table(self, columns):

/opt/conda/anaconda/lib/python3.6/site-packages/cartoframes/lib/context/api_context.py in upload(self, query, data)
     41 
     42     def upload(self, query, data):
---> 43         return self.copy_client.copyfrom(query.strip(), data)
     44 
     45     def execute_query(self, query, parse_json=True, do_post=True, format=None, **request_args):

/opt/conda/anaconda/lib/python3.6/site-packages/carto/sql.py in copyfrom(self, query, iterable_data, compress, compression_level)
    382             raise e
    383         except Exception as e:
--> 384             raise CartoException(e)
    385 
    386         return response_json

CartoException: ['Connection closed by server: input data too slow']
```

**Comment by alrocar** [comment] 2019-11-20 18:59
A fix in the COPY API has been deployed, see related [issue](https://github.com/CartoDB/support/issues/2239#issuecomment-556218123).

@djfan could you try to reproduce the issue?

Thanks!

**Comment by andy-esch** [comment] 2019-12-02 19:54
Just tried this and didn't experience the reported issues.

I mocked Dongjie's dataset like so:

```python
N = 110000
visits = {f"n_{n}": [randint(0, 25) for _ in range(N)] for n in range(24)}
visits["quadkey_id"] = (
    "".join(np.random.choice(list("0123"), size=16)) for _ in range(N)
)

# then create the polygon from the quadkey

df = gpd.GeoDataFrame(visits)
CartoDataFrame(df).to_carto(table_name="iss908_test", if_exists='replace')
```

The shape is approximately the same as the one Dongjie tried to upload as are most other data qualities.

**Comment by andy-esch** [comment] 2019-12-02 19:54
cc @Jesus89 ^^

**Comment by Jesus89** [comment] 2019-12-03 10:49
Awesome! Closing this :tada: 

Btw: you can create a CartoDataFrame directly from the visits variable.

**Closed by Jesus89** 2019-12-03 10:49 UTC
Labels: COPY, bug

**Comment by andy-esch** [comment] 2019-12-03 14:08
> Btw: you can create a CartoDataFrame directly from the visits variable.
Yes, it works! :) I was trying to save time with things I knew worked so didn't want to risk it before. Turns out it would've saved me 15 seconds ;)
