### ISSUE TITLE
column name collision is possible through DO metadata's `suggested_name`

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#323] opened 2017-12-09 04:02 UTC
This can cause problems because the user may not know which is which

**Comment by juanignaciosl** [comment] 2018-02-06 16:49
Could you provide a little more information about how to reproduce this, please?

**Comment by andy-esch** [comment] 2018-02-06 19:23
It's pretty interesting behavior.

1. Have a table with a column that the DO will suggest: https://team.carto.com/u/eschbacher/dataset/coordsmetro_demo
2. Augment data with the following query with a measure that will collide with it. cartoframes produces this query:
```sql
SELECT t.*, (data->0->>'value')::Numeric AS female_employed_incomplete_secondary_education_rate_2010, (data->1->>'value')::Numeric AS female_employed_incomplete_secondary_education_rate_2010
FROM OBS_GetData(
(SELECT array_agg((the_geom, cartodb_id)::geomval)
FROM "coordsmetro_demo"),
(SELECT '[{"index":14,"denom_aggregate":"sum","denom_colname":"employed_incomplete_secondary_education","denom_description":null,"denom_geomref_colname":"cvegeo","denom_id":"mx.inegi_columns.ECO13","denom_name":"Employed population with incomplete secondary education","denom_reltype":"denominator","denom_t_description":null,"denom_tablename":"obs_bbbeed134ba68308a4fac833514e6b7a5e5bdf11","denom_type":"Numeric","geom_colname":"the_geom","geom_description":"","geom_geomref_colname":"cvegeo","geom_id":"mx.inegi.municipio","geom_name":"Municipios","geom_t_description":null,"geom_tablename":"obs_366a1365508f0a27c925858ba2afb2d09884e576","geom_timespan":"2015","geom_type":"Geometry","id":10,"max_score_rank":null,"max_timespan_rank":null,"normalization":"denominated","num_geoms":5.8725732755,"numer_aggregate":"sum","numer_colname":"female_employed_incomplete_secondary_education","numer_description":null,"numer_geomref_colname":"cvegeo","numer_id":"mx.inegi_columns.ECO14","numer_name":"Employed female population with incomplete secondary education","numer_t_description":null,"numer_tablename":"obs_bbbeed134ba68308a4fac833514e6b7a5e5bdf11","numer_timespan":"2010","numer_type":"Numeric","score":36.600226087,"score_rank":1,"score_rownum":1,"suggested_name":"female_employed_incomplete_secondary_education_rate_2010","target_area":null,"target_geoms":null,"timespan_rank":1,"timespan_rownum":1},{"index":15,"denom_aggregate":"sum","denom_colname":"female_employed","denom_description":null,"denom_geomref_colname":"cvegeo","denom_id":"mx.inegi_columns.ECO5","denom_name":"Employed female","denom_reltype":"denominator","denom_t_description":null,"denom_tablename":"obs_bbbeed134ba68308a4fac833514e6b7a5e5bdf11","denom_type":"Numeric","geom_colname":"the_geom","geom_description":"","geom_geomref_colname":"cvegeo","geom_id":"mx.inegi.municipio","geom_name":"Municipios","geom_t_description":null,"geom_tablename":"obs_366a1365508f0a27c925858ba2afb2d09884e576","geom_timespan":"2015","geom_type":"Geometry","id":10,"max_score_rank":null,"max_timespan_rank":null,"normalization":"denominated","num_geoms":5.8725732755,"numer_aggregate":"sum","numer_colname":"female_employed_incomplete_secondary_education","numer_description":null,"numer_geomref_colname":"cvegeo","numer_id":"mx.inegi_columns.ECO14","numer_name":"Employed female population with incomplete secondary education","numer_t_description":null,"numer_tablename":"obs_bbbeed134ba68308a4fac833514e6b7a5e5bdf11","numer_timespan":"2010","numer_type":"Numeric","score":36.600226087,"score_rank":1,"score_rownum":2,"suggested_name":"female_employed_incomplete_secondary_education_rate_2010","target_area":null,"target_geoms":null,"timespan_rank":1,"timespan_rownum":2}]'::json)) as m,
coordsmetro_demo as t
WHERE t."cartodb_id" = m.id
```

I'm seeing some conflicting behaviors. When I run that query over the SQL API, I get `t.*` returned without the DO stuff. If I run it in Builder, I'll get a "NO Data" message _or_ a "column name female_employed_incomplete_secondary_education_rate_2010 ambiguous".

To combat that, I did a check in cartoframes to prevent the query from running in the first place: https://github.com/CartoDB/cartoframes/blob/6c1fddccdb4fd512053f7e01582068ce1984b787/cartoframes/context.py#L1618-L1622

## Script in cartoframes to reproduce

This is the script to generate the query above. Cartoframes Errors to avoid the problems discussed above.

```python
import cartoframes
import pandas as pd

# Enter your username and api key below
cc = cartoframes.CartoContext()
df = pd.read_excel('https://github.com/josecarlosgonz/mexicoCityMetro/blob/master/coordsMetro.xlsx?raw=true')
orig_table = 'coordsmetro_demo'
cc.write(df, orig_table, lnglat=('longitude_1', 'latitude_1'), overwrite=True)
meta = cc.data_discovery(
    region=orig_table,
    keywords='education',
    boundaries='mx.inegi.municipio')
# choose column names that collide with original table
meta = meta[meta.suggested_name == 'female_employed_incomplete_secondary_education_rate_2010']
# get data from DO -- this is where the `NameError` is thrown to avoid the issues above
data = cc.data(
    orig_table,
    meta[meta.suggested_name == 'female_employed_incomplete_secondary_education_rate_2010']
)

```

**Comment by andy-esch** [comment] 2018-02-06 19:39
Another issue here that crops up is that the DO suggests the same column name for the same measure with different denominators, as you can see in the JSON metadata sent through to `OBS_GetData`.

For example, if you run the following through the SQL API:
```sql
SELECT (data->0->>'value')::Numeric AS female_employed_incomplete_secondary_education_rate_2010, (data->1->>'value')::Numeric AS female_employed_incomplete_secondary_education_rate_2010
FROM OBS_GetData(
(SELECT array_agg((the_geom, cartodb_id)::geomval)
FROM "coordsmetro_demo"),
(SELECT '[{"index":14,"denom_aggregate":"sum","denom_colname":"employed_incomplete_secondary_education","denom_description":null,"denom_geomref_colname":"cvegeo","denom_id":"mx.inegi_columns.ECO13","denom_name":"Employed population with incomplete secondary education","denom_reltype":"denominator","denom_t_description":null,"denom_tablename":"obs_bbbeed134ba68308a4fac833514e6b7a5e5bdf11","denom_type":"Numeric","geom_colname":"the_geom","geom_description":"","geom_geomref_colname":"cvegeo","geom_id":"mx.inegi.municipio","geom_name":"Municipios","geom_t_description":null,"geom_tablename":"obs_366a1365508f0a27c925858ba2afb2d09884e576","geom_timespan":"2015","geom_type":"Geometry","id":10,"max_score_rank":null,"max_timespan_rank":null,"normalization":"denominated","num_geoms":5.8725732755,"numer_aggregate":"sum","numer_colname":"female_employed_incomplete_secondary_education","numer_description":null,"numer_geomref_colname":"cvegeo","numer_id":"mx.inegi_columns.ECO14","numer_name":"Employed female population with incomplete secondary education","numer_t_description":null,"numer_tablename":"obs_bbbeed134ba68308a4fac833514e6b7a5e5bdf11","numer_timespan":"2010","numer_type":"Numeric","score":36.600226087,"score_rank":1,"score_rownum":1,"suggested_name":"female_employed_incomplete_secondary_education_rate_2010","target_area":null,"target_geoms":null,"timespan_rank":1,"timespan_rownum":1},{"index":15,"denom_aggregate":"sum","denom_colname":"female_employed","denom_description":null,"denom_geomref_colname":"cvegeo","denom_id":"mx.inegi_columns.ECO5","denom_name":"Employed female","denom_reltype":"denominator","denom_t_description":null,"denom_tablename":"obs_bbbeed134ba68308a4fac833514e6b7a5e5bdf11","denom_type":"Numeric","geom_colname":"the_geom","geom_description":"","geom_geomref_colname":"cvegeo","geom_id":"mx.inegi.municipio","geom_name":"Municipios","geom_t_description":null,"geom_tablename":"obs_366a1365508f0a27c925858ba2afb2d09884e576","geom_timespan":"2015","geom_type":"Geometry","id":10,"max_score_rank":null,"max_timespan_rank":null,"normalization":"denominated","num_geoms":5.8725732755,"numer_aggregate":"sum","numer_colname":"female_employed_incomplete_secondary_education","numer_description":null,"numer_geomref_colname":"cvegeo","numer_id":"mx.inegi_columns.ECO14","numer_name":"Employed female population with incomplete secondary education","numer_t_description":null,"numer_tablename":"obs_bbbeed134ba68308a4fac833514e6b7a5e5bdf11","numer_timespan":"2010","numer_type":"Numeric","score":36.600226087,"score_rank":1,"score_rownum":2,"suggested_name":"female_employed_incomplete_secondary_education_rate_2010","target_area":null,"target_geoms":null,"timespan_rank":1,"timespan_rownum":2}]'::json)) as m,
coordsmetro_demo as t
WHERE t."cartodb_id" = m.id
```

CARTO **doesn't** complain that there are two columns of the same name, but only returns one of the columns. So users are not getting back all the data they request. I should probably add a check in cartoframes about this and update the column names as a workaround.

**Comment by juanignaciosl** [comment] 2018-02-12 13:03
> When I run that query over the SQL API, I get t.* returned without the DO stuff. If I run it in Builder, I'll get a "NO Data" message or a "column name female_employed_incomplete_secondary_education_rate_2010 ambiguous".

- Running it with the SQL API returns the last of the occurrences because json has unique keys. I've tried switching to CSV to workaround this, but it fails with "column reference is ambiguous".
- At Builder I always get "Analysis A1 failed: column "female_employed_incomplete_secondary_education_rate_2010" specified more than once" error, I don't get the same behaviour than you do (neither "no data" nor ambiguous error).

We can't fix the SQL API behaviour, and DO Analysis at Builder fails with a meaningful error, so I think that there's no much to do there. The check that you added to  CARTO Frames is nice. Do you think that we should do something else beyond that?

**Comment by juanignaciosl** [comment] 2018-02-21 10:25
Marked as blocked, waiting for a decision about this ^.

**Comment by andy-esch** [comment] 2018-02-21 18:45
My concern is that the user won't be able to get all the requested measures (from the metadata that's passed) since there are duplicate suggested column names -- but that's partly a separate issue -> https://github.com/CartoDB/bigmetadata/issues/418

To ensure that a user gets all the measures they request, we could update `CartoContext.data` to give new `suggested_names` if the metadata has duplicate names for different measures. Another fix would be to construct new names in cartoframes that takes into account the numerator and denominator instead of just saying 'rate'.

**Comment by juanignaciosl** [comment] 2018-02-22 12:26
Oh, ok. Thank you for clarifying CartoDB/bigmetadata/issues/418. I thought that the problematic collision there was between the table and the DO analysis, rather than between DO analysis measurements.

We've made a proposal that should avoid collisions within the analysis. When that's addressed, we can also improve CARTO Frames so it checks for collisions, because that's not something that can be addressed at SQL API level 👍

**Closed** 2018-02-26 17:49 UTC
Labels: bug, data observatory
