### ISSUE TITLE
Update Popups API

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartoframes#1348] opened 2019-12-12 07:36 UTC
Epic #1343
Related issue "Homogenize Popups/Legends/Widgets API" #1300

### 1. Change parameter parameter in Layer

* [x] `click_popup`
* [x] `hover_popup`

### 2. Add popup element

* [x] `popup_element`

```python
from cartoframes.viz.popups import click_popup, hover_popup

Layer(
    hover_popup=popup_element('name', title='Name')
)

Layer(
    hover_popup=[
        popup_element('name', title='Name')
    ],
    click_popup=[
        popup_element('name', title='Name'),
        popup_element('pop_max', title='Pop Max')
    ]
)
```

### ⚠️ 4. Docs!

This is an implicit task: update documentation

- [x] Guides
- [x] Reference
- [x] Examples

**Comment by elenatorro** [comment] 2019-12-18 14:18
Although we've already discussed the format and syntax of this refactor, there've been a couple of suggestions about changing it. I think we should review them before continuing, but remember we've limited time to implement last minute changes. 

**The problem**: `popups` is plural cause there're two kind of popups at the moment: `click` and `hover`. Howerver, having several `click_popup` and `hover_popup` elements could be confusing semantically.  Each popup has a **list of items**. Having this in mind, we've different suggestions:

Option 1:

```python
from cartoframes.viz import click_popup, hover_popup

popups=[
    click_popup(items=[
      ['pop_max', 'Max Population'],
      ['pop_min', 'Min Population']
    ]),
    hover_popup(items=[
      ['pop_min', 'Min Population']
    ])
]
```

Option 2:

```python
from cartoframes.viz import click_popup, hover_popup, popup_item

popups=[
  click_popup([
    popup_item('pop_max', title='Max Population')),
    popup_item('pop_min', title='Min Population'))
  ]),
  hover_popup([
    popup_item('pop_min', title='Min Population'))
  ])
]
```

Option 3:

```python
from cartoframes.viz import popups, popup_item

popups=popups(
    click=[
      popup_item('pop_max', title='Max Population'),
      popup_item('pop_min', title='Min Population')
    ],
    hover=[
      popup_item('pop_min', title='Min Population')
    ]
)
```


After thinking a while about it, I'd go for **option 3**

What do you think? cc @makella @andy-esch @cmongut @Jesus89

**Comment by Jesus89** [comment] 2019-12-18 14:26
Option 4:

from cartoframes.viz import popup_item

```py
popup_click=[
    popup_item('pop_max', title='Max Population'),
    popup_item('pop_min', title='Min Population')
],
popup_hover=[
    popup_item('pop_min', title='Min Population')
]
```

Semantics: a Layer has only a `popup` for click and hover. These popups are formed by a list of items.

**Comment by makella** [comment] 2019-12-18 14:47
could we remove the `popup_item` and just accept a list? or is that non-conventional?

```
from cartoframes.viz import popups

popups=popups(
    click=[
         ('pop_max', title='Max Population'),
         ('pop_min', title='Min Population')
    ],
    hover=[
         ('pop_min', title='Min Population')
    ]
)
```

**Comment by elenatorro** [comment] 2019-12-18 14:50
About @Jesus89's option:

I've a doubt, so do you mean having *two* parameters in the layer instead of one?

```py
Layer(
...
popup_click=[],
popup_chover=[]
)
```

Maybe I misunderstood it, but I don't really like that cause it breaks other conventions, I think we should keep using `popups` in plural.

About @makella's option:

We could, but the syntax would be as follows:

```python
from cartoframes.viz import popups

popups=popups(
    click=[
         ['pop_max', 'Max Population'],
         ['pop_min', 'Min Population']
    ],
    hover=[
         ['pop_min', 'Min Population']
    ]
)
```

I don't like this cause, altough the `popup_item` sounds verbose, it allows you to have named parameters (`title`, which could be extended in the future)  instead of just a list of lists

**Comment by Jesus89** [comment] 2019-12-18 15:03
> so do you mean having two parameters in the layer instead of one?

Yes

> tuples or lists

I would try to avoid using tuples, namedtuples or lists with positional params because they are harder to maintain, document and understand. I prefer using `popup_item` which provides a clear way of creating text items for the popups. In the future we can extend the helpers to create content for the popups, now it's only "title+text" but in the future, we can provide different shapes or styles.

**Comment by makella** [comment] 2019-12-18 15:04
i see so we wouldn't have named parameters available... yeah i'm finding the `popup_item` verbose but maybe it is just the words `popup_item`

**Comment by elenatorro** [comment] 2019-12-18 15:19
I don't really like the idea of having `popup_click` and `popup_hover` (or `hover_popup and `click_popup`, which is the correct syntax) at a layer level. The main reason is that having them in under a same entity makes it easier to control the objects altogether

**Comment by Jesus89** [comment] 2019-12-18 15:27
IMO, after opening this discussion, it's what makes more sense to me from the semantic point of view, because popups= is not a list anymore, and viz.popups should be a class, but a better name for that class should be PopupsConfig, so my 2 cents to split them at the Layer level.

**Comment by elenatorro** [comment] 2019-12-18 15:42
I get the idea that this is not a list anymore and agree with that, but again, in order to have control of both types of popup makes it difficult to control `popup` items as a group. I think that conceptually, it makes more sense to have click and hover popups in a same item through a single parameter.

Having said that, regarding implementation, this would require also a bit of extra time due to the JavaScript code would have to change as well and we'll have to refactor a higher amount of code. I know this is not a factor on deciding what's more semantically correct, just saying this in case it needs to be taken into account.

**Comment by elenatorro** [comment] 2019-12-18 15:44
Anyway, I'm ok with any solution, all of them same great to me. Having explained the technical issues, I think now the decision should be taken by Product, and once taken, we'll implement it.

**Comment by Jesus89** [comment] 2019-12-18 15:50
Yeah, since we have reviewed some times (:S) it would be nice to hear @cmongut and @andy-esch

**Comment by makella** [comment] 2019-12-18 15:52
i like the simplicity of option 3 (from the non-dev perspective!) and for me it seems the "closest" to the current implementation where a user is familiar with defining hover and click events in the same entity as @elenatorro mentions! i am thinking of an alternative to the name `popup_item` since that's the only part that feels funny to me but nothing is coming to my mind yet

love the discussion!

**Comment by cmongut** [comment] 2019-12-18 19:26
Hi team, thanks for trying to find a better solution and sorry for giving feedback at this point.

Options 1 are 2 are broken because they accept a list of elements but that list can't contain more than 2 elements. (I suggested option 2 initially)

After talking with @alejandrohall, we were discussing options 3 and 4.

- Option 3 seems good but it's a bit strange to have a method here, what about moving it to a dict?

```
popups={
    'click': [
    	popup_item('pop_max', title='Max Population'),
    	popup_item('pop_min', title='Min Population')
    ],
    'hover': [
    	popup_item('pop_min', title='Min Population')
    ]
}
```

- Option 4 makes sense because `click_popup` conceptually is the same as legends and widgets, a container. The issue is that we need to have two parameters instead of one.

Let's do a final round of thoughts and make the decision tomorrow

**Comment by elenatorro** [comment] 2019-12-19 08:59
Hi @cmongut thanks for taking a look. 

> Moving it to a dict

Actually, one of the main purposes of this task is to remove the dict, so we're not reverting that: we should avoid dicts for convention

**Comment by cmongut** [comment] 2019-12-19 11:21
Oki, we'll follow that convention then. I have been discussing some changes with @arredond for the option 4 as this one:

```
from cartoframes.viz import popup_item

click=[
    popup_item('pop_max', title='Max Population'),
    popup_item('pop_min', title='Min Population')
],
hover=[
    popup_item('pop_min', title='Min Population')
]
```

As this doesn't follow the naming convention as in legends and widgets, I would follow the option 4 as it was (with the naming change suggestion):

```
from cartoframes.viz import popup_item

click_popup=[
    popup_item('pop_max', title='Max Population'),
    popup_item('pop_min', title='Min Population')
],
hover_popup=[
    popup_item('pop_min', title='Min Population')
]
```

`popup_item` could be changed with `item`, `default_item`, etc. I don't know if we already have an element that does that.

**Comment by elenatorro** [comment] 2019-12-19 11:50
I'd propose to go for `popup_element` which, by default now is a text element. In the future, the `popup_element` could be extended in order to accept other types as **links** and **images** 👍

**Closed** 2019-12-23 08:22 UTC
Labels: refactor, visualization
