### ISSUE TITLE
Timeout on write operations

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartoframes#604] opened 2019-04-10 17:50 UTC
Doing some user testing of what's currently in the `master` branch I've hit timeouts on a write of a smallish sized dataframe (~3200 rows, three columns):
<img width="551" alt="Screen Shot 2019-04-10 at 1 49 27 PM" src="https://user-images.githubusercontent.com/1041056/55901522-7d300880-5b97-11e9-85b9-9b52475798fe.png">
Here's the data (zipped csv):
[over_limits.csv.zip](https://github.com/CartoDB/cartoframes/files/3065093/over_limits.csv.zip)

```python
cc.write(df, 'county_lq')
```
Gives:
```
RateLimitException: {"error":["You are over platform's limits: SQL query timeout error. Refactor your query before running again or contact CARTO support for more details."],"context":"limit","detail":"datasource"}
```

Full trace: <details><pre>/Users/aeschbacher/git/CartoDB/cartoframes/cartoframes/datasets.py:26: UserWarning: Table will be named `county_lq4`
  warn('Table will be named `{}`'.format(table_name))
/Users/aeschbacher/.local/share/virtualenvs/cartoframes-pRWzcuWT/src/carto/carto/sql.py:229: UserWarning: Batch SQL job created with job_id: 74e2d7d6-4256-491f-b5ac-5e6e94a106ee
  warnings.warn('Batch SQL job created with job_id: {job_id}'.format(job_id=data['job_id']))

---------------------------------------------------------------------------
RateLimitException                        Traceback (most recent call last)
~/.local/share/virtualenvs/cartoframes-pRWzcuWT/src/carto/carto/sql.py in copyfrom(self, query, iterable_data, compress, compression_level)
    379                                         stream=True)
--> 380             response_json = self.client.get_response_data(response)
    381         except CartoRateLimitException as e:

~/.local/share/virtualenvs/cartoframes-pRWzcuWT/lib/python3.7/site-packages/pyrestcli/auth.py in get_response_data(self, response, parse_json)
     59         elif response.status_code == requests.codes.too_many_requests:
---> 60             raise RateLimitException(_(response.text))
     61         else:

RateLimitException: {"error":["You are over platform's limits: SQL query timeout error. Refactor your query before running again or contact CARTO support for more details."],"context":"limit","detail":"datasource"}

During handling of the above exception, another exception occurred:

CartoException                            Traceback (most recent call last)
<ipython-input-11-59de86b5bd6b> in <module>
      1 sub = aug_data[['geoid', 'lq_month3_emplvl_10_total_all_industries_2017q1']]
----> 2 cc.write(sub, 'county_lq4')

~/git/CartoDB/cartoframes/cartoframes/context.py in write(self, df, table_name, temp_dir, overwrite, lnglat, encode_geom, geom_col, **kwargs)
    339             if_exists = Dataset.REPLACE
    340 
--> 341         dataset = dataset.upload(with_lonlat=lnglat, if_exists=if_exists)
    342 
    343         tqdm.write('Table successfully written to CARTO: {table_url}'.format(

~/git/CartoDB/cartoframes/cartoframes/datasets.py in upload(self, with_lonlat, if_exists)
     40                 self._create_table(with_lonlat)
     41 
---> 42         self._copyfrom(with_lonlat)
     43 
     44         return self

~/git/CartoDB/cartoframes/cartoframes/datasets.py in _copyfrom(self, with_lonlat)
     96             """COPY {table_name}({columns},the_geom)
     97                FROM stdin WITH (FORMAT csv, DELIMITER '|');""".format(table_name=self.table_name, columns=columns),
---> 98             self._rows(self.df, self.df.columns, with_lonlat, geom_col)
     99         )
    100 

~/.local/share/virtualenvs/cartoframes-pRWzcuWT/src/carto/carto/sql.py in copyfrom(self, query, iterable_data, compress, compression_level)
    382             raise e
    383         except Exception as e:
--> 384             raise CartoException(e)
    385 
    386         return response_json

CartoException: {"error":["You are over platform's limits: SQL query timeout error. Refactor your query before running again or contact CARTO support for more details."],"context":"limit","detail":"datasource"}</pre></details>

cc @alrocar

**Comment by alrocar** [comment] 2019-04-10 18:28
Probably another case of [this issue](https://github.com/CartoDB/CartoDB-SQL-API/issues/579)

Does it work if you choose a different table name?

cc. @oleurud

**Comment by andy-esch** [comment] 2019-04-10 18:38
I get inconsistent behavior. Sometimes it uploads very fast, other times it stalls and times out on new tablename, etc..

**Comment by oleurud** [comment] 2019-04-10 19:34
Yes, it seems like https://github.com/CartoDB/CartoDB-SQL-API/issues/579 but without a Python error.

Only a question: are you trying to upload data to the same table at the same time? Concurrent requests to the same table will have this problem: the first one locks the table and the second (and successive) will have to wait.

**Comment by andy-esch** [comment] 2019-04-10 20:13
I did a `overwrite='replace'` of an existing table (different from above) about 5 minutes after the last write completed successfully and still got the timeout. Then did another write 1 minute later and it completed successfully. And another 30 seconds after that worked too. Now I can't reproduce

**Comment by alrocar** [comment] 2019-05-08 15:17
@andy-esch While reviewing the rate limits (for a different project) I've realized that this issue could be a legit case of rate limiting. The problem might not be the size of the csv or the csv itself, but the execution of the notebook (number of requests).

Did you do those tests you mention with your team account?

**Comment by andy-esch** [comment] 2019-05-08 15:30
Team account if I recall correctly

**Comment by dgaubert** [comment] 2019-05-31 13:07
Regarding the issue description, the limit error is a database timeout limit. When you reach a rate-limit error, the error is: `429 (Too Many Requests): You are over platform's limits. Please contact us to know more details`.  You can fall in it easily, with a dozen request to `copyfrom` sequentially.

We return a database timeout when the underlying error coming from Postgres contains the following:
  - `statement timeout`
  - `RuntimeError: Execution of function interrupted by signal`
  - `canceling statement due to user request`

As we were having issues with locked tables in team's database ins that timeframe and we were manually terminating `copyfrom` queries, it might the original error was `Execution of function interrupted by signal`. So it might be a false alarm.. or not...

I need more context to know what's happening with this issue. Please @andy-esch, can you try again to see if the issue is still happening?

**Comment by dgaubert** [comment] 2019-05-31 13:21
Forgot to mention, I've created a script trying to reproduce the error but I did not have luck.

```js
// indes.js
'use strict'

const fs = require('fs')
const fetch = require('node-fetch')

if (!process.env.USER || !process.env.API_KEY || !process.env.FILEPATH_A || !process.env.FILEPATH_B || !process.env.TIMES) {
  console.log('Missing env variables USER, API_KEY, FILEPATH, TIMES')
  process.exit(1)
}

const queryURL = ({ user = process.env.USER, apikey = process.env.API_KEY } = {}) => `https://${user}.carto.com/api/v1/sql?api_key=${apikey}`
const composeTableName = ({ timestamp = Date.now() } = {}) => `populated_places_test_${timestamp}`
const createTableQuery = ({ tablename = composeTableName() } = {}) => `CREATE TABLE ${tablename} (the_geom public.geometry(Geometry, 4326), note text, natscale integer, labelrank integer, featurecla text, name text, namepar text, namealt text, diffascii integer, nameascii text, adm0cap double precision, capalt double precision, capin text, worldcity double precision, megacity integer, sov0name text, adm0name text, adm0_a3 text, adm1name text, scalerank integer, cartodb_id integer NOT NULL, latitude double precision, longitude double precision, changed double precision, namediff integer, diffnote text, pop_max integer, pop_min integer, pop_other integer, rank_max integer, rank_min integer, geonameid double precision, meganame text, ls_name text, ls_match integer, checkme integer, created_at date, updated_at date, iso_a2 text, sov_a3 text, _feature_count integer DEFAULT 1)`
const dropTableQuery = ({ tablename = composeTableName() } = {}) => `DROP TABLE ${tablename}`

const copyfromQuery = ({ tablename }) => `COPY ${tablename}(the_geom, note, natscale, labelrank, featurecla, name, namepar, namealt, diffascii, nameascii, adm0cap, capalt, capin, worldcity, megacity, sov0name, adm0name, adm0_a3, adm1name, scalerank, cartodb_id, latitude, longitude, changed, namediff, diffnote, pop_max, pop_min, pop_other, rank_max, rank_min, geonameid, meganame, ls_name, ls_match, checkme, created_at, updated_at, iso_a2, sov_a3, _feature_count) FROM STDIN WITH (FORMAT csv, HEADER true)`
const copyfromURL = ({ user = process.env.USER, apikey = process.env.API_KEY, query } = {}) => `https://${user}.carto.com/api/v1/sql/copyfrom?api_key=${apikey}&q=${query}`

const randomMs = () => Math.ceil(Math.random() * 1000)
const wait = (ms) => new Promise(resolve => setTimeout(() => resolve(), ms))

async function createTable () {
  const tablename = composeTableName();
  const url = queryURL()
  const opts = {
    method: 'post',
    body: `{ "q": "${createTableQuery({ tablename })}" }`,
    headers: { 'Content-Type': 'application/json' }
  }

  const res = await fetch(url, opts)

  if (res.status !== 200) {
    throw new Error(`${res.status}: ${res.statusText}`)
  }

  console.log(`Table ${tablename} successfully created!`)

  return tablename;
}

async function populateTable ({ tablename, filepath }) {
  const query = copyfromQuery({ tablename })
  const url = copyfromURL({ query })
  const opts = {
    method: 'post',
    body: fs.createReadStream(filepath),
    headers: {
      'Content-Type': 'application/octet-stream',
      'Transfer-Encoding': 'chunked'
    }
  }

  const res = await fetch(url, opts)


  if (res.status !== 200) {
    const body = await res.json()
    throw new Error(`${res.status} (${res.statusText}): ${body.error[0]}`)
  }

  const body = await res.json()

  console.log(`Table ${tablename} populated with ${body.total_rows} rows in ${body.time} ms successfully`);
}

async function dropTable ({ tablename }) {
  const url = queryURL()
  const opts = {
    method: 'post',
    body: `{ "q": "${dropTableQuery({ tablename })}" }`,
    headers: { 'Content-Type': 'application/json' }
  }

  const res = await fetch(url, opts)

  if (res.status !== 200) {
    throw new Error(`${res.status}: ${res.statusText}`)
  }

  console.log(`Table ${tablename} successfully dropped!`)
}

async function createTables () {
  const tablenames = []
  for (let index = 0; index < process.env.TIMES; index++) {
    const tablename = await createTable()
    tablenames.push(tablename)
  }

  return tablenames
}

async function populateTables ({ tablenames, filepath }) {
  for (const tablename of tablenames) {
    await populateTable({ tablename, filepath })
    await wait(randomMs())
  }
}

async function dropTables ({ tablenames }) {
  for (const tablename of tablenames) {
    await dropTable({ tablename })
  }
}

async function sequential () {
  try {
    for (let index = 0; index < process.env.TIMES; index++) {
      const tablename = await createTable()
      await populateTable({ tablename, filepath: process.env.FILEPATH_A })
      await populateTable({ tablename, filepath: process.env.FILEPATH_B })
      await dropTable({ tablename })
      await wait(randomMs())
      if (index < process.env.TIMES - 1) {
        console.log('---')
      }
    }
  } catch (err) {
    console.error(err)
  }
}

async function batches () {
  try {
    const tablenames = await createTables()
    console.log('---')
    await populateTables({ tablenames, filepath: process.env.FILEPATH_A })
    console.log('---')
    await populateTables({ tablenames, filepath: process.env.FILEPATH_B })
    console.log('---')
    await dropTables({ tablenames })
  } catch (err) {
    console.error(err)
  }
}

async function main() {
  switch (process.env.MODE) {
    case 'batches':
      await batches()
      break;

    default:
      await sequential()
      break;
  }
}

main()
```

To run the script:
```
USER={user} API_KEY={apikey} FILEPATH_A=./populated_places_test_a.csv FILEPATH_B=./populated_places_test_b.csv TIMES=50 node index.js
```

Creates and populates a table with two different `.csv` files 50 times sequentially. And the only error that I got is a legit `rate-limit` error.

**Comment by andy-esch** [comment] 2019-06-07 18:27
I'm trying my best to re-create the issue but having no success, which maybe is a good thing. I'll ping back here if I see it again.

**Comment by dgaubert** [comment] 2019-06-10 07:06
Closing then.

**Closed by dgaubert** 2019-06-10 07:06 UTC
Labels: 1.0
